### PR TITLE
README: Add "Add a repo" section

### PR DESCRIPTION
**Pull request by roberth**
:rainbow: polyrepo :unicorn:

### CODE REVIEW

**Comment by domenkozar** [comment]
It would be better to just schedule hourly build, as our documentation grows that is a one-time setup cost.

This is going to be painful to maintain, when we really need something quicker we can manually trigger it.

**Comment by roberth** [comment]
It wasn't painful. Waiting for an avg half hour is painful because of the context switching.
We can do hourly as a catch-all though.

**Comment by domenkozar** [comment]
> painful because of the context switching.

Why is there a need for context switching, documentation preview should be part of the upstream repo, so there's nothing to do here.

**Comment by roberth** [comment]
This doc looks a lot scarier than it really is. It's all pretty much default and it worked on the first try.

> painful

I don't trust the setup 100% yet, so I want to manually verify that it deploys.

**Comment by domenkozar** [comment]
Assuming hourly build runs **and** we verify it, deployed via github actions, is something you can rely on (if it fails, it will send an email).

Push setup, however, requires manual intervention and thus most importantly someone to **remember to set it up**.

I'm nowhere saying this is scary, rather than suboptimial workflow wise (although optimal with response time, which I'm arguing are not an issue).

**Comment by roberth** [comment]
Doing hourly will require us to pay for extra minutes.
I don't think we'll have a better setup for this anytime soon. Let's merge this so it's out of the way and to make it documented until we find the time to implement something better.

**Comment by domenkozar** [comment]
#79

**Pull request closed without merging**
